Repository hlxsites/elco-aerotop-sg, pull requests merged in 2023-02, with the labels that each got.

#101 fix: responsive font styling
  blocks/explosion-slider/explosion-slider.css
  styles/styles.css
Labels: enhancement

#108 feat: hero styling
  blocks/hero/hero.css
Labels: enhancement

#109 fix: padding for sections with padding set to 10vw
  styles/styles.css
Labels: bug

#94 feat: adjust headings on home page
  blocks/columns/columns.css
  styles/styles.css
Labels: enhancement

#100 fix: progress bar mobile styling
  blocks/progress-bar-table/progress-bar-table.css
Labels: bug

#103 feat: martech integrations
  .eslintignore
  head.html
  scripts/delayed.js
  scripts/partytown-atomics.js
  scripts/partytown-media.js
  scripts/partytown-sw.js
  scripts/partytown.js
Labels: enhancement

#105 fix: spacing
  styles/styles.css
Labels: bug

#113 fix: home/dark hover button effect
  styles/styles.css
Labels: bug

#115 feat: multi-lingual indices and sitemap
  helix-query.yaml
  helix-sitemap.yaml
Labels: configuration

#141 feat: basic font-fallback
  styles/lazy-styles.css
  styles/styles.css
Labels: enhancement
